<a href="https://colab.research.google.com/github/PraveenGanapa/Basic-Virtual-Piano/blob/master/fraud_transaction_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import  pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [6]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [7]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27819 entries, 0 to 27818
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    27819 non-null  int64
 1   V1      27818 non-null  float64
 2   V2      27818 non-null  float64
 3   V3      27818 non-null  float64
 4   V4      27818 non-null  float64
 5   V5      27818 non-null  float64
 6   V6      27818 non-null  float64
 7   V7      27818 non-null  float64
 8   V8      27818 non-null  float64
 9   V9      27818 non-null  float64
 10  V10     27818 non-null  float64
 11  V11     27818 non-null  float64
 12  V12     27818 non-null  float64
 13  V13     27818 non-null  float64
 14  V14     27818 non-null  float64
 15  V15     27818 non-null  float64
 16  V16     27818 non-null  float64
 17  V17     27818 non-null  float64
 18  V18     27818 non-null  float64
 19  V19     27818 non-null  float64
 20  V20     27818 non-null  float64
 21  V21     27818 non-null  float64
 22  V22     27818 non-null  float64
 23  V23     27818 non-null  float64
 24  V24     27818 non-null  float64
 25  V25     27818 non-null  float64
 26  V26     27818 non-null  float64
 27  V27     27818 non-null  float64
 28  V28     27818 non-null  float64
 29  Amount  27818 non-null  float64
 30  Class   27818 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 6.6 MB

In [8]:
credit_card_data.isnull().sum()

Time      0
V1        1
V2        1
V3        1
V4        1
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [11]:
credit_card_data['Class'].value_counts()

0.0    27725
1.0       93
Name: Class, dtype: int64

In [15]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [16]:
print(legit.shape)
print(fraud.shape)

(27725, 31)
(93, 31)

In [17]:
legit.Amount.describe()

count    27725.000000
mean        77.232517
std        219.509762
min          0.000000
25%          6.490000
50%         19.950000
75%         69.320000
max       7879.420000
Name: Amount, dtype: float64

In [18]:
fraud.Amount.describe()

count      93.000000
mean       96.609677
std       259.128010
min         0.000000
25%         1.000000
50%         1.100000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [52]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,20440.754518,-0.190595,0.129284,0.765200,0.201632,-0.180681,0.092904,-0.099318,0.014884,0.405538,...,0.041673,-0.037007,-0.125822,-0.040202,0.011510,0.129192,0.022983,0.010650,0.003732,77.232517
1.0,18829.451613,-8.165086,6.134379,-11.690379,6.070066,-5.753486,-2.388962,-7.986805,4.121062,-2.922478,...,0.697894,0.549621,-0.372248,-0.340859,-0.260055,0.359772,0.179521,0.832824,0.100500,96.609677

In [25]:
legit_sample = legit.sample(n=492)

In [26]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [27]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
7509,10254,-0.366698,0.668497,2.368016,1.242119,-0.224208,1.093536,-0.312947,0.428233,1.327611,...,-0.046134,0.302239,-0.095643,-0.370709,-0.513636,-0.342910,0.200293,0.140958,12.99,0.0
22465,32260,0.928109,-0.416534,1.273992,1.861894,-1.004141,0.411151,-0.489297,0.287882,1.336329,...,-0.362564,-0.755340,0.075082,0.377596,0.331895,-0.533864,0.074359,0.041839,76.84,0.0
23323,32698,-1.341888,0.284113,1.887340,0.172680,1.268763,0.153436,0.786326,-0.006910,-0.409335,...,-0.065160,0.097334,-0.154253,-0.295048,0.741726,-0.424786,-0.231727,-0.148988,9.99,0.0
6798,8565,-1.384305,1.039127,1.957868,-1.631141,0.529895,0.250339,0.897775,-0.468799,2.704753,...,-0.461666,-0.161372,-0.070448,-0.381953,-0.511766,0.621705,-0.116903,-0.499593,2.31,0.0
4704,4129,-0.766312,0.579711,2.316592,1.442345,-0.359837,-0.343325,0.120095,0.017702,1.399369,...,0.083819,0.700013,-0.022721,0.702805,-0.051898,-0.232212,0.387479,0.220472,59.76,0.0

In [28]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
26802,34256,0.539276,1.554890,-2.066180,3.241617,0.184736,0.028330,-1.515521,0.537035,-1.999846,...,0.371773,0.111955,-0.305225,-1.053835,0.771175,0.240878,0.418435,0.232170,19.02,1.0
27362,34521,1.081234,0.416414,0.862919,2.520863,-0.005021,0.563341,-0.123372,0.223122,-0.673598,...,-0.159387,-0.305154,0.053620,0.011761,0.375146,-0.106299,0.021008,0.010559,1.52,1.0
27627,34634,0.333499,1.699873,-2.596561,3.643945,-0.585068,-0.654659,-2.275789,0.675229,-2.042416,...,0.469212,-0.144363,-0.317981,-0.769644,0.807855,0.228164,0.551002,0.305473,18.96,1.0
27738,34684,-2.439237,2.591458,-2.840126,1.286244,-1.777016,-1.436139,-2.206056,-2.282725,-0.292885,...,1.774460,-0.771390,0.065727,0.103916,-0.057578,0.242652,-0.268649,-0.743713,125.30,1.0
27749,34687,-0.860827,3.131790,-5.052968,5.420941,-2.494141,-1.811287,-5.479117,1.189472,-3.908206,...,1.192694,0.090356,-0.341881,-0.215924,1.053032,0.271139,1.373300,0.691195,19.02,1.0

In [29]:
new_dataset['Class'].value_counts()

0.0    492
1.0     93
Name: Class, dtype: int64

In [31]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,21290.670732,-0.236962,0.202334,0.735325,0.155484,-0.101617,0.068254,-0.103418,0.005166,0.389977,...,-0.007302,-0.007302,-0.139151,0.011918,0.044850,0.120968,0.042984,0.023031,0.004582,62.922581
1.0,18829.451613,-8.165086,6.134379,-11.690379,6.070066,-5.753486,-2.388962,-7.986805,4.121062,-2.922478,...,0.697894,0.549621,-0.372248,-0.340859,-0.260055,0.359772,0.179521,0.832824,0.100500,96.609677

In [32]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [33]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
7509   10254 -0.366698  0.668497  2.368016  1.242119 -0.224208  1.093536
22465  32260  0.928109 -0.416534  1.273992  1.861894 -1.004141  0.411151
23323  32698 -1.341888  0.284113  1.887340  0.172680  1.268763  0.153436
6798    8565 -1.384305  1.039127  1.957868 -1.631141  0.529895  0.250339
4704    4129 -0.766312  0.579711  2.316592  1.442345 -0.359837 -0.343325
...      ...       ...       ...       ...       ...       ...       ...
26802  34256  0.539276  1.554890 -2.066180  3.241617  0.184736  0.028330
27362  34521  1.081234  0.416414  0.862919  2.520863 -0.005021  0.563341
27627  34634  0.333499  1.699873 -2.596561  3.643945 -0.585068 -0.654659
27738  34684 -2.439237  2.591458 -2.840126  1.286244 -1.777016 -1.436139
27749  34687 -0.860827  3.131790 -5.052968  5.420941 -2.494141 -1.811287

             V7        V8        V9  ...       V20       V21       V22  \
7509  -0.312947  0.428233  1.327611  ... -0.044719 -0.046134  0.302239
22465 -0.489297  0.287882  1.336329  ... -0.133929 -0.362564 -0.755340
23323  0.786326 -0.006910 -0.409335  ... -0.089367 -0.065160  0.097334
6798   0.897775 -0.468799  2.704753  ...  0.580252 -0.461666 -0.161372
4704   0.120095  0.017702  1.399369  ...  0.317403  0.083819  0.700013
...         ...       ...       ...  ...       ...       ...       ...
26802 -1.515521  0.537035 -1.999846  ...  0.302735  0.371773  0.111955
27362 -0.123372  0.223122 -0.673598  ... -0.165249 -0.159387 -0.305154
27627 -2.275789  0.675229 -2.042416  ...  0.329342  0.469212 -0.144363
27738 -2.206056 -2.282725 -0.292885  ...  0.513530  1.774460 -0.771390
27749 -5.479117  1.189472 -3.908206  ...  1.085760  1.192694  0.090356

            V23       V24       V25       V26       V27       V28  Amount
7509  -0.095643 -0.370709 -0.513636 -0.342910  0.200293  0.140958   12.99
22465  0.075082  0.377596  0.331895 -0.533864  0.074359  0.041839   76.84
23323 -0.154253 -0.295048  0.741726 -0.424786 -0.231727 -0.148988    9.99
6798  -0.070448 -0.381953 -0.511766  0.621705 -0.116903 -0.499593    2.31
4704  -0.022721  0.702805 -0.051898 -0.232212  0.387479  0.220472   59.76
...         ...       ...       ...       ...       ...       ...     ...
26802 -0.305225 -1.053835  0.771175  0.240878  0.418435  0.232170   19.02
27362  0.053620  0.011761  0.375146 -0.106299  0.021008  0.010559    1.52
27627 -0.317981 -0.769644  0.807855  0.228164  0.551002  0.305473   18.96
27738  0.065727  0.103916 -0.057578  0.242652 -0.268649 -0.743713  125.30
27749 -0.341881 -0.215924  1.053032  0.271139  1.373300  0.691195   19.02

[585 rows x 30 columns]

In [34]:
print(Y)

7509     0.0
22465    0.0
23323    0.0
6798     0.0
4704     0.0
        ...
26802    1.0
27362    1.0
27627    1.0
27738    1.0
27749    1.0
Name: Class, Length: 585, dtype: float64

In [38]:
X_train, X_test, Y_train, Y_test, = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [39]:
print(X.shape, X_train.shape, X_test.shape)

(585, 30) (468, 30) (117, 30)

In [42]:
modal = LogisticRegression()

In [ ]:
modal.fit(X_train, Y_train)

In [46]:
X_train_prediction = modal.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [47]:
print('accuracy on training data :', training_data_accuracy)

accuracy on training data : 0.9807692307692307

In [50]:
X_test_prediction = modal.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [51]:
print('accuracy score on test data :',test_data_accuracy)

accuracy score on test data : 0.9829059829059829